providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "poetry"]

[phases.install]
cmds = [
  "poetry config virtualenvs.in-project true",
  "poetry lock || true",
  "poetry install --no-interaction"
]

[start]
cmd = "poetry run python -m rapid_reports_ai.main"

