providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "poetry"]

[phases.install]
cmds = [
  "cd backend && poetry config virtualenvs.create false",
  "cd backend && poetry install --only main"
]

[start]
cmd = "cd backend && poetry run python -m rapid_reports_ai.main"

